[target.riscv64gc-unknown-linux-musl]
linker = "/opt/riscv-musl/bin/riscv64-buildroot-linux-musl-gcc.br_real"
rustflags = [
    "-C", "target-feature=-crt-static",
    "-C", "link-arg=--sysroot=/opt/riscv-musl/riscv64-buildroot-linux-musl/sysroot",
    "-L/opt/riscv-musl/riscv64-buildroot-linux-musl/sysroot/lib",
    "-L/opt/riscv-musl/lib/gcc/riscv64-buildroot-linux-musl/12.3.0",
    # "-C", "target-feature=+crt-static", # Uncomment me to force static compilation
    #"-C", "panic=abort", # Uncomment me to avoid compiling in panics
]

# TODO: fix riscv sdk
[env]
CC_riscv64gc-unknown-linux-musl = "/home/andreas/embedded/duo-buildroot-sdk/host-tools/gcc/riscv64-linux-musl-x86_64/bin/riscv64-unknown-linux-musl-gcc"
