[http]
listen_address = "0.0.0.0"
listen_port = 8080

[influx]
url = "http://192.168.178.33"
port = "8086"
db = "homeassistant"
user = "root"
password = ""
id = "heatpump"
delta_t_sec = 10

[[measurement_points]]
sensor_id = "28-3ce1e3806031"
name = "BufferLow"

[[measurement_points]]
sensor_id = "28-3ce1e3805fbe"
name = "CirculationPumpIn"

[[measurement_points]]
sensor_id = "28-3ce1e38083ed"
name = "CirculationPumpOut"